/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DsgMinter__factory } from "./DsgMinter__factory";
export { NftMinter__factory } from "./NftMinter__factory";
